# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j6JEEHFLSNXAJJ5jwdw_HBCo2Y4gvyKO
"""

!pip install catboost

!pip install optuna
!pip install catboost

pip install catboost

!pip install streamlit

# app.py
import streamlit as st
import pandas as pd
import numpy as np
import pickle
from catboost import CatBoostRegressor
from datetime import datetime

# === LOAD MODEL ===
with open("catboost_model_quikr.pkl", "rb") as f:
    model = pickle.load(f)

# === KONFIGURASI HALAMAN ===
st.set_page_config(page_title="Prediksi Harga Mobil Bekas", layout="centered")

# === SIDEBAR ===
st.sidebar.title("🔧 Input Data Mobil")
st.sidebar.markdown("Silakan masukkan data mobil bekas untuk mendapatkan estimasi harga jual.")

# === PILIHAN INPUT ===
company_models = sorted([
    'Audi_Audi', 'BMW_BMW', 'Chevrolet_Chevrolet', 'Datsun_Datsun', 'Fiat_Fiat',
    'Force_Force', 'Ford_Ford', 'Hindustan_Hindustan', 'Honda_Honda', 'Hyundai_Hyundai',
    'Jeep_Jeep', 'Mahindra_Mahindra', 'Maruti_Maruti', 'Mercedes_Mercedes', 'Mitsubishi_Mitsubishi',
    'Nissan_Nissan', 'Renault_Renault', 'Skoda_Skoda', 'Tata_Tata', 'Toyota_Toyota',
    'Volkswagen_Volkswagen', 'Daihatsu_Daihatsu', 'Wuling_Wuling', 'Mazda_Mazda', 'Chery_Chery'
])
fuel_types = ['Petrol', 'Diesel', 'Hybrid']

company_model = st.sidebar.selectbox("Merek & Model", company_models)
fuel_type = st.sidebar.selectbox("Jenis Bahan Bakar", fuel_types)
age = st.sidebar.slider("Umur Mobil (tahun)", 0, 30, 5)
kms_driven = st.sidebar.number_input("Jarak Tempuh (KM)", min_value=0, step=1000)

# === VALIDASI DASAR ===
if age == 0 and kms_driven > 20000:
    st.sidebar.warning("Mobil baru biasanya tidak menempuh >20.000 KM.")

# === ESTIMASI SEGMENTASI ===
base_prices = {
    'Audi_Audi': 650_000_000,
    'BMW_BMW': 700_000_000,
    'Mercedes_Mercedes': 750_000_000,
    'Toyota_Toyota': 350_000_000,
    'Honda_Honda': 300_000_000,
    'Hyundai_Hyundai': 250_000_000,
    'Maruti_Maruti': 120_000_000,
    'Tata_Tata': 110_000_000,
    'Daihatsu_Daihatsu': 130_000_000,
    'Wuling_Wuling': 150_000_000
}
estimated_price = base_prices.get(company_model, 200_000_000)
segment = pd.cut([estimated_price],
    bins=[0, 80e6, 150e6, 300e6, 500e6, 1e9, 3e9],
    labels=['ultra_low', 'low', 'mid_low', 'mid_high', 'high', 'lux']
)[0]

# === FITUR TURUNAN ===
fuel_age = f"{fuel_type}_{age}"
company_segment = f"{company_model}_{segment}"
log_km = np.log1p(kms_driven)
log_km_per_year = np.log1p(kms_driven / max(age, 1))

# === BRAND CATEGORY ===
lux_brands = ['BMW_BMW', 'Mercedes_Mercedes', 'Audi_Audi', 'Land_Rover_Land']
mid_brands = ['Toyota_Toyota', 'Honda_Honda', 'Hyundai_Hyundai', 'Volkswagen_Volkswagen', 'Mazda_Mazda']
budget_brands = ['Tata_Tata', 'Datsun_Datsun', 'Maruti_Maruti', 'Hindustan_Hindustan', 'Force_Force', 'Fiat_Fiat', 'Daihatsu_Daihatsu', 'Wuling_Wuling']

if company_model in lux_brands:
    brand_category = 'luxury'
elif company_model in mid_brands:
    brand_category = 'midrange'
elif company_model in budget_brands:
    brand_category = 'budget'
else:
    brand_category = 'general'

is_premium = int(brand_category == 'luxury' and age <= 3)
is_high_value = int(brand_category in ['luxury', 'midrange'] and age <= 5 and kms_driven <= 60000)
is_low_budget = int(brand_category == 'budget' and age >= 10 and kms_driven >= 120000)

# === BENTUKKAN DATA UNTUK PREDIKSI ===
features = pd.DataFrame([{
    'company_model': company_model,
    'fuel_type': fuel_type,
    'log_km': log_km,
    'age': age,
    'segment': segment,
    'fuel_age': fuel_age,
    'company_segment': company_segment,
    'log_km_per_year': log_km_per_year,
    'brand_category': brand_category,
    'is_premium': is_premium,
    'is_high_value': is_high_value,
    'is_low_budget': is_low_budget
}])

# === TOMBOL PREDIKSI ===
st.title("🚗 Prediksi Harga Mobil Bekas")

if st.button("🔍 Prediksi Harga"):
    pred_log = model.predict(features)[0]
    pred_rp = np.expm1(pred_log)

    st.success(f"💰 Estimasi Harga: **Rp {pred_rp:,.0f}**")
    st.markdown(f"**Kategori Merek:** `{brand_category}`")
    st.markdown(f"**Segmentasi Harga:** `{segment}`")

    # Simpan ke CSV (opsional)
    log_data = features.copy()
    log_data['predicted_price'] = pred_rp
    log_data['timestamp'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    log_data.to_csv("history_log.csv", mode='a', index=False, header=False)