# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j6JEEHFLSNXAJJ5jwdw_HBCo2Y4gvyKO
"""

# app.py
import streamlit as st
import pandas as pd
import numpy as np
import pickle
from datetime import datetime

# === Load model ===
with open("catboost_model_quikr.pkl", "rb") as f:
    model = pickle.load(f)

# === Load dataset untuk dropdown ===
df = pd.read_csv("Quikr_Cars_Cleaned_Dataset.csv")
df["name"] = df["name"].str.strip()
company_models = sorted(df["name"].unique())
fuel_types = ['Petrol', 'Diesel', 'Hybrid']

# === Streamlit layout ===
st.set_page_config(page_title="Prediksi Harga Mobil Bekas", layout="centered")
st.title("🚗 Prediksi Harga Mobil Bekas")

st.sidebar.title("Input Mobil")
company_model = st.sidebar.selectbox("Pilih Merek & Model", company_models)
fuel_type = st.sidebar.selectbox("Jenis Bahan Bakar", fuel_types)
age = st.sidebar.slider("Umur Mobil (tahun)", 0, 30, 5)
kms_driven = st.sidebar.number_input("Jarak Tempuh (KM)", min_value=0, step=1000)

# Validasi input
if age == 0 and kms_driven > 20000:
    st.sidebar.warning("Mobil baru biasanya belum menempuh lebih dari 20.000 KM.")

# Estimasi harga dasar berdasarkan brand
brand = company_model.split()[0]
base_prices = {
    'Audi': 650_000_000,
    'BMW': 700_000_000,
    'Mercedes': 750_000_000,
    'Toyota': 350_000_000,
    'Honda': 300_000_000,
    'Hyundai': 250_000_000,
    'Maruti': 120_000_000,
    'Tata': 110_000_000,
    'Daihatsu': 130_000_000,
    'Wuling': 150_000_000
}
estimated_price = base_prices.get(brand, 200_000_000)
segment = pd.cut([estimated_price],
    bins=[0, 80e6, 150e6, 300e6, 500e6, 1e9, 3e9],
    labels=['ultra_low', 'low', 'mid_low', 'mid_high', 'high', 'lux']
)[0]

# Fitur turunan
fuel_age = f"{fuel_type}_{age}"
company_segment = f"{company_model}_{segment}"
log_km = np.log1p(kms_driven)
log_km_per_year = np.log1p(kms_driven / max(age, 1))

# Kategori brand
lux_brands = ['BMW', 'Mercedes', 'Audi']
mid_brands = ['Toyota', 'Honda', 'Hyundai', 'Volkswagen', 'Mazda']
budget_brands = ['Tata', 'Maruti', 'Daihatsu', 'Wuling']

if brand in lux_brands:
    brand_category = 'luxury'
elif brand in mid_brands:
    brand_category = 'midrange'
elif brand in budget_brands:
    brand_category = 'budget'
else:
    brand_category = 'general'

is_premium = int(brand_category == 'luxury' and age <= 3)
is_high_value = int(brand_category in ['luxury', 'midrange'] and age <= 5 and kms_driven <= 60000)
is_low_budget = int(brand_category == 'budget' and age >= 10 and kms_driven >= 120000)

# Data input
features = pd.DataFrame([{
    'company_model': company_model,
    'fuel_type': fuel_type,
    'log_km': log_km,
    'age': age,
    'segment': segment,
    'fuel_age': fuel_age,
    'company_segment': company_segment,
    'log_km_per_year': log_km_per_year,
    'brand_category': brand_category,
    'is_premium': is_premium,
    'is_high_value': is_high_value,
    'is_low_budget': is_low_budget
}])

# Prediksi
if st.button("🔍 Prediksi Harga"):
    pred_log = model.predict(features)[0]
    pred_rp = np.expm1(pred_log)

    st.success(f"💰 Estimasi Harga: **Rp {pred_rp:,.0f}**")
    st.markdown(f"**Brand Category:** `{brand_category}`")
    st.markdown(f"**Segment:** `{segment}`")

    # Simpan ke log
    features['predicted_price'] = pred_rp
    features['timestamp'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    features.to_csv("history_log.csv", mode='a', header=False, index=False)